using AdvWorksAPI.EntityLayer;

namespace AdvWorksAPI.RepositoryLayer;

/// <summary>
/// This class creates some fake data for the Customer table.
/// </summary>
public class CustomerRepository
{
  #region Get Method
  /// <summary>
  /// Get all Customer objects
  /// </summary>
  /// <returns>A list of Customer objects</returns>
  public List<Customer> Get()
  {
    return new List<Customer>
    {
      new Customer {
         CustomerID = 1,
         Title = "Mr.",
         FirstName = "Orlando",
         MiddleName = "N.",
         LastName = "Gee",
         CompanyName = "A Bike Store",
         EmailAddress = "orlando0adventure-works.com",
         Phone = "245-555-0173",
         ModifiedDate = Convert.ToDateTime("3/11/2019 2:20:33 PM"),
      },
      new Customer {
         CustomerID = 2,
         Title = "Mr.",
         FirstName = "Keith",
         MiddleName = "asdf",
         LastName = "Harris",
         CompanyName = "Progressive Sports",
         EmailAddress = "keith0adventure-works.com",
         Phone = "170-555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 3,
         Title = "Ms.",
         FirstName = "Donna",
         MiddleName = null,
         LastName = "Carreras",
         CompanyName = "Advanced Bike Components",
         EmailAddress = "donna0adventure-works.com",
         Phone = "279-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 4,
         Title = "Ms.",
         FirstName = "Janet",
         MiddleName = "M.",
         LastName = "Gates",
         CompanyName = "Modular Cycle Systems",
         EmailAddress = "janet1adventure-works.com",
         Phone = "710-555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 5,
         Title = "Mr.",
         FirstName = "Lucy",
         MiddleName = null,
         LastName = "Harrington",
         CompanyName = "Metropolitan Sports Supply",
         EmailAddress = "lucy0adventure-works.com",
         Phone = "828-555-0186",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 6,
         Title = "Ms.",
         FirstName = "Rosmarie",
         MiddleName = "J.",
         LastName = "Carroll",
         CompanyName = "Aerobic Exercise Company",
         EmailAddress = "rosmarie0adventure-works.com",
         Phone = "244-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 7,
         Title = "Mr.",
         FirstName = "Dominic",
         MiddleName = "P.",
         LastName = "Gash",
         CompanyName = "Associated Bikes",
         EmailAddress = "dominic0adventure-works.com",
         Phone = "192-555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 10,
         Title = "Ms.",
         FirstName = "Kathleen",
         MiddleName = "M.",
         LastName = "Garza",
         CompanyName = "Rural Cycle Emporium",
         EmailAddress = "kathleen0adventure-works.com",
         Phone = "150-555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 11,
         Title = "Ms.",
         FirstName = "Katherine",
         MiddleName = null,
         LastName = "Harding",
         CompanyName = "Sharp Bikes",
         EmailAddress = "katherine0adventure-works.com",
         Phone = "926-555-0159",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 12,
         Title = "Mr.",
         FirstName = "Johnny",
         MiddleName = "A.",
         LastName = "Caprio",
         CompanyName = "Bikes and Motorbikes",
         EmailAddress = "johnny0adventure-works.com",
         Phone = "112-555-0191",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 16,
         Title = "Mr.",
         FirstName = "Christopher",
         MiddleName = "R.",
         LastName = "Beck",
         CompanyName = "Bulk Discount Store",
         EmailAddress = "christopher1adventure-works.com",
         Phone = "1 (11) 500 555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 18,
         Title = "Mr.",
         FirstName = "David",
         MiddleName = "J.",
         LastName = "Liu",
         CompanyName = "Catalog Store",
         EmailAddress = "david20adventure-works.com",
         Phone = "440-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 19,
         Title = "Mr.",
         FirstName = "John",
         MiddleName = "A.",
         LastName = "Beaver",
         CompanyName = "Center Cycle Shop",
         EmailAddress = "john8adventure-works.com",
         Phone = "521-555-0195",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 20,
         Title = "Ms.",
         FirstName = "Jean",
         MiddleName = "P.",
         LastName = "Handley",
         CompanyName = "Central Discount Store",
         EmailAddress = "jean1adventure-works.com",
         Phone = "582-555-0113",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 21,
         Title = null,
         FirstName = "Jinghao",
         MiddleName = null,
         LastName = "Liu",
         CompanyName = "Chic Department Stores",
         EmailAddress = "jinghao1adventure-works.com",
         Phone = "928-555-0116",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 22,
         Title = "Ms.",
         FirstName = "Linda",
         MiddleName = "E.",
         LastName = "Burnett",
         CompanyName = "Travel Systems",
         EmailAddress = "linda4adventure-works.com",
         Phone = "121-555-0121",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 23,
         Title = "Mr.",
         FirstName = "Kerim",
         MiddleName = null,
         LastName = "Hanif",
         CompanyName = "Bike World",
         EmailAddress = "kerim0adventure-works.com",
         Phone = "216-555-0122",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 24,
         Title = "Mr.",
         FirstName = "Kevin",
         MiddleName = null,
         LastName = "Liu",
         CompanyName = "Eastside Department Store",
         EmailAddress = "kevin5adventure-works.com",
         Phone = "926-555-0164",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 25,
         Title = "Mr.",
         FirstName = "Donald",
         MiddleName = "L.",
         LastName = "Blanton",
         CompanyName = "Coalition Bike Company",
         EmailAddress = "donald0adventure-works.com",
         Phone = "357-555-0161",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 28,
         Title = "Ms.",
         FirstName = "Jackie",
         MiddleName = "E.",
         LastName = "Blackwell",
         CompanyName = "Commuter Bicycle Store",
         EmailAddress = "jackie0adventure-works.com",
         Phone = "972-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 29,
         Title = "Mr.",
         FirstName = "Bryan",
         MiddleName = null,
         LastName = "Hamilton",
         CompanyName = "Cross-Country Riding Supplies",
         EmailAddress = "bryan2adventure-works.com",
         Phone = "344-555-0144",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 30,
         Title = "Mr.",
         FirstName = "Todd",
         MiddleName = "R.",
         LastName = "Logan",
         CompanyName = "Cycle Merchants",
         EmailAddress = "todd0adventure-works.com",
         Phone = "783-555-0110",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 34,
         Title = "Ms.",
         FirstName = "Barbara",
         MiddleName = "J.",
         LastName = "German",
         CompanyName = "Cycles Wholesaler & Mfg.",
         EmailAddress = "barbara4adventure-works.com",
         Phone = "1 (11) 500 555-0181",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 37,
         Title = "Mr.",
         FirstName = "Jim",
         MiddleName = null,
         LastName = "Geist",
         CompanyName = "Two Bike Shops",
         EmailAddress = "jim1adventure-works.com",
         Phone = "724-555-0161",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 38,
         Title = "Ms.",
         FirstName = "Betty",
         MiddleName = "M.",
         LastName = "Haines",
         CompanyName = "Finer Mart",
         EmailAddress = "betty0adventure-works.com",
         Phone = "867-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 39,
         Title = "Ms.",
         FirstName = "Sharon",
         MiddleName = "J.",
         LastName = "Looney",
         CompanyName = "Fitness Hotel",
         EmailAddress = "sharon2adventure-works.com",
         Phone = "377-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 40,
         Title = "Mr.",
         FirstName = "Darren",
         MiddleName = null,
         LastName = "Gehring",
         CompanyName = "Journey Sporting Goods",
         EmailAddress = "darren0adventure-works.com",
         Phone = "417-555-0182",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 41,
         Title = "Ms.",
         FirstName = "Erin",
         MiddleName = "M.",
         LastName = "Hagens",
         CompanyName = "Distant Inn",
         EmailAddress = "erin1adventure-works.com",
         Phone = "244-555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 42,
         Title = "Mr.",
         FirstName = "Jeremy",
         MiddleName = null,
         LastName = "Los",
         CompanyName = "Healthy Activity Store",
         EmailAddress = "jeremy0adventure-works.com",
         Phone = "911-555-0165",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 43,
         Title = "Ms.",
         FirstName = "Elsa",
         MiddleName = null,
         LastName = "Leavitt",
         CompanyName = "Frugal Bike Shop",
         EmailAddress = "elsa0adventure-works.com",
         Phone = "482-555-0174",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 46,
         Title = "Mr.",
         FirstName = "David",
         MiddleName = "O",
         LastName = "Lawrence",
         CompanyName = "Gear-Shift Bikes Limited",
         EmailAddress = "david19adventure-works.com",
         Phone = "653-555-0159",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 47,
         Title = "Ms.",
         FirstName = "Hattie",
         MiddleName = "J.",
         LastName = "Haemon",
         CompanyName = "Greater Bike Store",
         EmailAddress = "hattie0adventure-works.com",
         Phone = "141-555-0172",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 48,
         Title = "Ms.",
         FirstName = "Anita",
         MiddleName = "R.",
         LastName = "Lucerne",
         CompanyName = "Grand Industries",
         EmailAddress = "anita0adventure-works.com",
         Phone = "164-555-0118",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 52,
         Title = "Ms.",
         FirstName = "Rebecca",
         MiddleName = null,
         LastName = "Laszlo",
         CompanyName = "Instruments and Parts Company",
         EmailAddress = "rebecca2adventure-works.com",
         Phone = "1 (11) 500 555-0155",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 55,
         Title = "Mr.",
         FirstName = "Eric",
         MiddleName = null,
         LastName = "Lang",
         CompanyName = "Kickstands and Accessories Company",
         EmailAddress = "eric6adventure-works.com",
         Phone = "932-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 56,
         Title = "Mr.",
         FirstName = "Brian",
         MiddleName = null,
         LastName = "Groth",
         CompanyName = "Latest Accessories Sales",
         EmailAddress = "brian5adventure-works.com",
         Phone = "461-555-0118",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 57,
         Title = "Ms.",
         FirstName = "Judy",
         MiddleName = "R.",
         LastName = "Lundahl",
         CompanyName = "Leading Sales & Repair",
         EmailAddress = "judy1adventure-works.com",
         Phone = "260-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 58,
         Title = "Mr.",
         FirstName = "Peter",
         MiddleName = null,
         LastName = "Kurniawan",
         CompanyName = "Largest Bike Store",
         EmailAddress = "peter4adventure-works.com",
         Phone = "436-555-0160",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 59,
         Title = "Mr.",
         FirstName = "Douglas",
         MiddleName = null,
         LastName = "Groncki",
         CompanyName = "Locks Company",
         EmailAddress = "douglas2adventure-works.com",
         Phone = "385-555-0140",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 60,
         Title = "Mr.",
         FirstName = "Sean",
         MiddleName = "J.",
         LastName = "Lunt",
         CompanyName = "Main Bicycle Services",
         EmailAddress = "sean4adventure-works.com",
         Phone = "183-555-0111",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 61,
         Title = "Mr.",
         FirstName = "Jeffrey",
         MiddleName = null,
         LastName = "Kurtz",
         CompanyName = "Many Bikes Store",
         EmailAddress = "jeffrey3adventure-works.com",
         Phone = "452-555-0179",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 64,
         Title = "Mr.",
         FirstName = "Vamsi",
         MiddleName = null,
         LastName = "Kuppa",
         CompanyName = "Metal Clearing House",
         EmailAddress = "vamsi1adventure-works.com",
         Phone = "290-555-0196",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 65,
         Title = "Ms.",
         FirstName = "Jane",
         MiddleName = "P.",
         LastName = "Greer",
         CompanyName = "Metro Manufacturing",
         EmailAddress = "jane2adventure-works.com",
         Phone = "737-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 66,
         Title = "Mr.",
         FirstName = "Alexander",
         MiddleName = "J.",
         LastName = "Deborde",
         CompanyName = "Neighborhood Store",
         EmailAddress = "alexander1adventure-works.com",
         Phone = "394-555-0176",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 70,
         Title = "Mr.",
         FirstName = "Deepak",
         MiddleName = null,
         LastName = "Kumar",
         CompanyName = "Outdoor Aerobic Systems Company",
         EmailAddress = "deepak0adventure-works.com",
         Phone = "1 (11) 500 555-0122",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 73,
         Title = "Ms.",
         FirstName = "Margaret",
         MiddleName = "T.",
         LastName = "Krupka",
         CompanyName = "Outdoor Sports Supply",
         EmailAddress = "margaret1adventure-works.com",
         Phone = "107-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 74,
         Title = "Mr.",
         FirstName = "Christopher",
         MiddleName = "M.",
         LastName = "Bright",
         CompanyName = "Parcel Express Delivery Service",
         EmailAddress = "christopher2adventure-works.com",
         Phone = "162-555-0166",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 75,
         Title = "Ms.",
         FirstName = "Aidan",
         MiddleName = null,
         LastName = "Delaney",
         CompanyName = "Paint Supply",
         EmailAddress = "aidan0adventure-works.com",
         Phone = "358-555-0188",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 76,
         Title = "Mr.",
         FirstName = "James",
         MiddleName = "J.",
         LastName = "Krow",
         CompanyName = "Out-of-the-Way Hotels",
         EmailAddress = "james11adventure-works.com",
         Phone = "265-555-0190",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 77,
         Title = "Mr.",
         FirstName = "Michael",
         MiddleName = null,
         LastName = "Brundage",
         CompanyName = "Mechanical Products Ltd.",
         EmailAddress = "michael13adventure-works.com",
         Phone = "128-555-0148",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 78,
         Title = "Mr.",
         FirstName = "Stefan",
         MiddleName = null,
         LastName = "Delmarco",
         CompanyName = "Preferred Bikes",
         EmailAddress = "stefan0adventure-works.com",
         Phone = "819-555-0186",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 79,
         Title = "Mr.",
         FirstName = "Mitch",
         MiddleName = null,
         LastName = "Kennedy",
         CompanyName = "Reasonable Bicycle Sales",
         EmailAddress = "mitch0adventure-works.com",
         Phone = "996-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 82,
         Title = "Mr.",
         FirstName = "James",
         MiddleName = "D.",
         LastName = "Kramer",
         CompanyName = "Refined Department Stores",
         EmailAddress = "james10adventure-works.com",
         Phone = "814-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 83,
         Title = "Mr.",
         FirstName = "Eric",
         MiddleName = "J.",
         LastName = "Brumfield",
         CompanyName = "Requisite Part Supply",
         EmailAddress = "eric3adventure-works.com",
         Phone = "644-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 84,
         Title = "Ms.",
         FirstName = "Della",
         MiddleName = "F.",
         LastName = "Demott Jr",
         CompanyName = "Rewarding Activities Company",
         EmailAddress = "della0adventure-works.com",
         Phone = "752-555-0185",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 88,
         Title = "Ms.",
         FirstName = "Pamala",
         MiddleName = "M.",
         LastName = "Kotc",
         CompanyName = "Closest Bicycle Store",
         EmailAddress = "pamala0adventure-works.com",
         Phone = "1 (11) 500 555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 91,
         Title = "Ms.",
         FirstName = "Joy",
         MiddleName = "R.",
         LastName = "Koski",
         CompanyName = "Scooters and Bikes Store",
         EmailAddress = "joy0adventure-works.com",
         Phone = "810-555-0198",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 92,
         Title = "Ms.",
         FirstName = "Jovita",
         MiddleName = "A.",
         LastName = "Carmody",
         CompanyName = "Sports Commodities",
         EmailAddress = "jovita0adventure-works.com",
         Phone = "646-555-0137",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 93,
         Title = "Mr.",
         FirstName = "Prashanth",
         MiddleName = null,
         LastName = "Desai",
         CompanyName = "Stationary Bikes and Stands",
         EmailAddress = "prashanth0adventure-works.com",
         Phone = "138-555-0156",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 94,
         Title = "Mr.",
         FirstName = "Scott",
         MiddleName = null,
         LastName = "Konersmann",
         CompanyName = "Specialty Sports Store",
         EmailAddress = "scott6adventure-works.com",
         Phone = "556-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 95,
         Title = "Ms.",
         FirstName = "Jane",
         MiddleName = "N.",
         LastName = "Carmichael",
         CompanyName = "Rural Department Store",
         EmailAddress = "jane0adventure-works.com",
         Phone = "716-555-0167",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 96,
         Title = "Ms.",
         FirstName = "Bonnie",
         MiddleName = "B.",
         LastName = "Lepro",
         CompanyName = "More Bikes!",
         EmailAddress = "bonnie2adventure-works.com",
         Phone = "354-555-0130",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 97,
         Title = "Mr.",
         FirstName = "Eugene",
         MiddleName = null,
         LastName = "Kogan",
         CompanyName = "Mountain Bike Center",
         EmailAddress = "eugene2adventure-works.com",
         Phone = "136-555-0134",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 100,
         Title = "Mr.",
         FirstName = "Kirk",
         MiddleName = "T",
         LastName = "King",
         CompanyName = "Up-To-Date Sports",
         EmailAddress = "kirk2adventure-works.com",
         Phone = "979-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 101,
         Title = "Mr.",
         FirstName = "William",
         MiddleName = "J.",
         LastName = "Conner",
         CompanyName = "Urban Sports Emporium",
         EmailAddress = "william1adventure-works.com",
         Phone = "383-555-0111",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 102,
         Title = "Ms.",
         FirstName = "Linda",
         MiddleName = null,
         LastName = "Leste",
         CompanyName = "National Manufacturing",
         EmailAddress = "linda7adventure-works.com",
         Phone = "493-555-0134",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 106,
         Title = "Ms.",
         FirstName = "Andrea",
         MiddleName = "A.",
         LastName = "Thomsen",
         CompanyName = "West Side Mart",
         EmailAddress = "andrea1adventure-works.com",
         Phone = "1 (11) 500 555-0120",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 109,
         Title = "Mr.",
         FirstName = "Daniel",
         MiddleName = "P.",
         LastName = "Thompson",
         CompanyName = "Travel Sports",
         EmailAddress = "daniel2adventure-works.com",
         Phone = "247-555-0197",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 110,
         Title = "Ms.",
         FirstName = "Kendra",
         MiddleName = "N.",
         LastName = "Thompson",
         CompanyName = "Vintage Sport Boutique",
         EmailAddress = "kendra0adventure-works.com",
         Phone = "464-555-0188",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 111,
         Title = "Mr.",
         FirstName = "Scott",
         MiddleName = "A.",
         LastName = "Colvin",
         CompanyName = "Westside Cycle Store",
         EmailAddress = "scott1adventure-works.com",
         Phone = "119-555-0144",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 112,
         Title = "Ms.",
         FirstName = "Elsie",
         MiddleName = "L.",
         LastName = "Lewin",
         CompanyName = "Town Industries",
         EmailAddress = "elsie0adventure-works.com",
         Phone = "803-555-0116",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 113,
         Title = "Mr.",
         FirstName = "Donald",
         MiddleName = "M.",
         LastName = "Thompson",
         CompanyName = "Trendy Department Stores",
         EmailAddress = "donald1adventure-works.com",
         Phone = "273-555-0111",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 114,
         Title = "Mr.",
         FirstName = "John",
         MiddleName = "L.",
         LastName = "Colon",
         CompanyName = "Two Wheels Cycle Store",
         EmailAddress = "john14adventure-works.com",
         Phone = "397-555-0144",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 115,
         Title = "Mr.",
         FirstName = "George",
         MiddleName = "Z.",
         LastName = "Li",
         CompanyName = "Security Racks and Locks Wholesalers",
         EmailAddress = "george3adventure-works.com",
         Phone = "699-555-0183",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 118,
         Title = "Mr.",
         FirstName = "Yale",
         MiddleName = null,
         LastName = "Li",
         CompanyName = "Rapid Bikes",
         EmailAddress = "yale0adventure-works.com",
         Phone = "316-555-0138",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 119,
         Title = "Ms.",
         FirstName = "Phyllis",
         MiddleName = "A.",
         LastName = "Thomas",
         CompanyName = "Red Bicycle Company",
         EmailAddress = "phyllis2adventure-works.com",
         Phone = "667-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 120,
         Title = "Mr.",
         FirstName = "Pat",
         MiddleName = null,
         LastName = "Coleman",
         CompanyName = "Machines & Cycles Store",
         EmailAddress = "pat2adventure-works.com",
         Phone = "292-555-0128",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 124,
         Title = "Ms.",
         FirstName = "Yuhong",
         MiddleName = null,
         LastName = "Li",
         CompanyName = "Nearby Sporting Goods",
         EmailAddress = "yuhong1adventure-works.com",
         Phone = "1 (11) 500 555-0176",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 127,
         Title = "Mr.",
         FirstName = "Joseph",
         MiddleName = "M.",
         LastName = "Lique",
         CompanyName = "Front Sporting Goods",
         EmailAddress = "joseph2adventure-works.com",
         Phone = "119-555-0195",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 128,
         Title = "Ms.",
         FirstName = "Judy",
         MiddleName = "J.",
         LastName = "Thames",
         CompanyName = "Demand Distributors",
         EmailAddress = "judy3adventure-works.com",
         Phone = "799-555-0118",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 129,
         Title = "Ms.",
         FirstName = "Connie",
         MiddleName = "L.",
         LastName = "Coffman",
         CompanyName = "Discount Bicycle Specialists",
         EmailAddress = "connie0adventure-works.com",
         Phone = "426-555-0181",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 130,
         Title = "Mr.",
         FirstName = "Paulo",
         MiddleName = "H.",
         LastName = "Lisboa",
         CompanyName = "Elite Bikes",
         EmailAddress = "paulo0adventure-works.com",
         Phone = "380-555-0116",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 131,
         Title = "Ms.",
         FirstName = "Vanessa",
         MiddleName = "J.",
         LastName = "Tench",
         CompanyName = "Eighth Bike Store",
         EmailAddress = "vanessa0adventure-works.com",
         Phone = "785-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 132,
         Title = "Ms.",
         FirstName = "Teanna",
         MiddleName = "M.",
         LastName = "Cobb",
         CompanyName = "Another Sporting Goods Company",
         EmailAddress = "teanna0adventure-works.com",
         Phone = "661-555-0168",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 133,
         Title = "Mr.",
         FirstName = "Michael",
         MiddleName = null,
         LastName = "Graff",
         CompanyName = "Commercial Sporting Goods",
         EmailAddress = "michael16adventure-works.com",
         Phone = "132-555-0150",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 136,
         Title = "Mr.",
         FirstName = "Derek",
         MiddleName = null,
         LastName = "Graham",
         CompanyName = "Wholesale Parts",
         EmailAddress = "derek0adventure-works.com",
         Phone = "674-555-0187",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 137,
         Title = null,
         FirstName = "Gytis",
         MiddleName = "M",
         LastName = "Barzdukas",
         CompanyName = "Transportation Options",
         EmailAddress = "gytis0adventure-works.com",
         Phone = "257-555-0119",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 138,
         Title = "Ms.",
         FirstName = "Jane",
         MiddleName = null,
         LastName = "Clayton",
         CompanyName = "South Bike Company",
         EmailAddress = "jane1adventure-works.com",
         Phone = "206-555-0195",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 142,
         Title = "Mr.",
         FirstName = "Jon",
         MiddleName = null,
         LastName = "Grande",
         CompanyName = "Riding Cycles",
         EmailAddress = "jon1adventure-works.com",
         Phone = "1 (11) 500 555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 145,
         Title = "Mr.",
         FirstName = "Ted",
         MiddleName = null,
         LastName = "Bremer",
         CompanyName = "Raw Materials Inc",
         EmailAddress = "ted0adventure-works.com",
         Phone = "962-555-0166",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 146,
         Title = "Mr.",
         FirstName = "Richard",
         MiddleName = null,
         LastName = "Bready",
         CompanyName = "Latest Sports Equipment",
         EmailAddress = "richard1adventure-works.com",
         Phone = "340-555-0131",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 147,
         Title = "Ms.",
         FirstName = "Alice",
         MiddleName = null,
         LastName = "Clark",
         CompanyName = "Local Hardware Factory",
         EmailAddress = "alice1adventure-works.com",
         Phone = "221-555-0141",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 148,
         Title = "Mr.",
         FirstName = "Alan",
         MiddleName = null,
         LastName = "Brewer",
         CompanyName = "Lots of Bikes Storehouse",
         EmailAddress = "alan1adventure-works.com",
         Phone = "494-555-0134",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 149,
         Title = "Mr.",
         FirstName = "Cornelius",
         MiddleName = "L.",
         LastName = "Brandon",
         CompanyName = "Initial Bike Company",
         EmailAddress = "cornelius0adventure-works.com",
         Phone = "229-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 150,
         Title = "Ms.",
         FirstName = "Jill",
         MiddleName = "J.",
         LastName = "Christie",
         CompanyName = "Fleet Bikes",
         EmailAddress = "jill1adventure-works.com",
         Phone = "927-555-0198",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 151,
         Title = "Mr.",
         FirstName = "Walter",
         MiddleName = "J.",
         LastName = "Brian",
         CompanyName = "Futuristic Bikes",
         EmailAddress = "walter0adventure-works.com",
         Phone = "163-555-0155",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 154,
         Title = "Mr.",
         FirstName = "Carlton",
         MiddleName = "M.",
         LastName = "Carlisle",
         CompanyName = "Camping and Sports Store",
         EmailAddress = "carlton0adventure-works.com",
         Phone = "193-555-0116",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 155,
         Title = "Mr.",
         FirstName = "Joseph",
         MiddleName = "N.",
         LastName = "Castellucio",
         CompanyName = "Corner Bicycle Supply",
         EmailAddress = "joseph1adventure-works.com",
         Phone = "180-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 156,
         Title = "Mr.",
         FirstName = "Lester",
         MiddleName = "J.",
         LastName = "Bowman",
         CompanyName = "Metal Processing Company",
         EmailAddress = "lester0adventure-works.com",
         Phone = "844-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 160,
         Title = "Ms.",
         FirstName = "Brigid",
         MiddleName = "F.",
         LastName = "Cavendish",
         CompanyName = "Vigorous Sports Store",
         EmailAddress = "brigid0adventure-works.com",
         Phone = "1 (11) 500 555-0178",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 163,
         Title = "Mr.",
         FirstName = "Andrew",
         MiddleName = null,
         LastName = "Cencini",
         CompanyName = "Sports Merchandise",
         EmailAddress = "andrew2adventure-works.com",
         Phone = "644-555-0111",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 164,
         Title = "Ms.",
         FirstName = "Cindy",
         MiddleName = "M.",
         LastName = "Dodd",
         CompanyName = "Suburban Cycle Shop",
         EmailAddress = "cindy0adventure-works.com",
         Phone = "706-555-0140",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 165,
         Title = "Mr.",
         FirstName = "Randall",
         MiddleName = null,
         LastName = "Boseman",
         CompanyName = "Third Bike Store",
         EmailAddress = "randall0adventure-works.com",
         Phone = "383-555-0117",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 166,
         Title = "Ms.",
         FirstName = "Stacey",
         MiddleName = "M.",
         LastName = "Cereghino",
         CompanyName = "Fitness Toy Store",
         EmailAddress = "stacey0adventure-works.com",
         Phone = "351-555-0131",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 167,
         Title = "Mr.",
         FirstName = "Blaine",
         MiddleName = null,
         LastName = "Dockter",
         CompanyName = "Farthermost Bike Shop",
         EmailAddress = "blaine0adventure-works.com",
         Phone = "156-555-0187",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 168,
         Title = "Sr.",
         FirstName = "Luis",
         MiddleName = null,
         LastName = "Bonifaz",
         CompanyName = "Economy Bikes Company",
         EmailAddress = "luis0adventure-works.com",
         Phone = "688-555-0113",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 169,
         Title = "Ms.",
         FirstName = "Brenda",
         MiddleName = null,
         LastName = "Diaz",
         CompanyName = "Downtown Hotel",
         EmailAddress = "brenda2adventure-works.com",
         Phone = "147-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 172,
         Title = "Ms.",
         FirstName = "Gabriele",
         MiddleName = null,
         LastName = "Dickmann",
         CompanyName = "Certified Sports Supply",
         EmailAddress = "gabriele0adventure-works.com",
         Phone = "835-555-0116",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 173,
         Title = "Mr.",
         FirstName = "Rudolph",
         MiddleName = "J.",
         LastName = "Dillon",
         CompanyName = "Sundry Sporting Goods",
         EmailAddress = "rudolph0adventure-works.com",
         Phone = "722-555-0169",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 174,
         Title = "Mr.",
         FirstName = "Michael",
         MiddleName = "L.",
         LastName = "Bohling",
         CompanyName = "Toy Manufacturing Inc",
         EmailAddress = "michael12adventure-works.com",
         Phone = "838-555-0147",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 178,
         Title = "Mr.",
         FirstName = "Dick",
         MiddleName = null,
         LastName = "Dievendorff",
         CompanyName = "Rampart Amusement Company",
         EmailAddress = "dick1adventure-works.com",
         Phone = "1 (11) 500 555-0193",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 180,
         Title = "Ms.",
         FirstName = "Nicky",
         MiddleName = "E.",
         LastName = "Chesnut",
         CompanyName = "Full-Service Bike Store",
         EmailAddress = "nicky0adventure-works.com",
         Phone = "264-555-0164",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 181,
         Title = "Mr.",
         FirstName = "Michael",
         MiddleName = "J.",
         LastName = "Lee",
         CompanyName = "Family Entertainment Center",
         EmailAddress = "michael18adventure-works.com",
         Phone = "396-555-0139",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 182,
         Title = "Mr.",
         FirstName = "Stanley",
         MiddleName = "A.",
         LastName = "Alan",
         CompanyName = "Another Bicycle Company",
         EmailAddress = "stanley0adventure-works.com",
         Phone = "156-555-0126",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 183,
         Title = "Mr.",
         FirstName = "Yao-Qiang",
         MiddleName = null,
         LastName = "Cheng",
         CompanyName = "This Area Sporting Goods",
         EmailAddress = "yao-qiang0adventure-works.com",
         Phone = "344-555-0181",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 184,
         Title = "Ms.",
         FirstName = "Marjorie",
         MiddleName = "M.",
         LastName = "Lee",
         CompanyName = "Go-cart and Bike Specialists",
         EmailAddress = "marjorie0adventure-works.com",
         Phone = "306-555-0166",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 185,
         Title = "Mr.",
         FirstName = "Sandeep",
         MiddleName = null,
         LastName = "Kaliyath",
         CompanyName = "Weekend Bike Tours",
         EmailAddress = "sandeep1adventure-works.com",
         Phone = "495-555-0113",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 186,
         Title = "Mr.",
         FirstName = "Pei",
         MiddleName = null,
         LastName = "Chow",
         CompanyName = "Thrilling Bike Tours",
         EmailAddress = "pei0adventure-works.com",
         Phone = "789-555-0184",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 187,
         Title = "Mr.",
         FirstName = "Frank",
         MiddleName = null,
         LastName = "Campbell",
         CompanyName = "Trailblazing Sports",
         EmailAddress = "frank4adventure-works.com",
         Phone = "491-555-0132",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 190,
         Title = "Mr.",
         FirstName = "Mark",
         MiddleName = null,
         LastName = "Lee",
         CompanyName = "Racing Partners",
         EmailAddress = "mark5adventure-works.com",
         Phone = "371-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 191,
         Title = "Ms.",
         FirstName = "Sandra",
         MiddleName = "T.",
         LastName = "Kitt",
         CompanyName = "Non-Slip Pedal Company",
         EmailAddress = "sandra2adventure-works.com",
         Phone = "303-555-0117",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 192,
         Title = "Mr.",
         FirstName = "Hao",
         MiddleName = null,
         LastName = "Chen",
         CompanyName = "Nuts and Bolts Mfg.",
         EmailAddress = "hao1adventure-works.com",
         Phone = "117-555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 196,
         Title = "Ms.",
         FirstName = "Jolie",
         MiddleName = null,
         LastName = "Lenehan",
         CompanyName = "Exhibition Showroom",
         EmailAddress = "jolie0adventure-works.com",
         Phone = "1 (11) 500 555-0126",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 197,
         Title = "Ms.",
         FirstName = "Diane",
         MiddleName = "F.",
         LastName = "Krane",
         CompanyName = "Fabrikam Inc., West",
         EmailAddress = "diane4adventure-works.com",
         Phone = "224-555-0126",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 198,
         Title = "Mr.",
         FirstName = "Payton",
         MiddleName = "P.",
         LastName = "Benson",
         CompanyName = "Field Trip Inc",
         EmailAddress = "payton0adventure-works.com",
         Phone = "528-555-0183",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 199,
         Title = "Mr.",
         FirstName = "Roger",
         MiddleName = null,
         LastName = "Lengel",
         CompanyName = "Authorized Bike Sales and Rental",
         EmailAddress = "roger1adventure-works.com",
         Phone = "947-555-0143",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 200,
         Title = "Ms.",
         FirstName = "Peggy",
         MiddleName = "J.",
         LastName = "Justice",
         CompanyName = "Basic Bike Company",
         EmailAddress = "peggy0adventure-works.com",
         Phone = "170-555-0189",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 201,
         Title = "Ms.",
         FirstName = "Edna",
         MiddleName = "J.",
         LastName = "Benson",
         CompanyName = "Unsurpassed Bikes",
         EmailAddress = "edna0adventure-works.com",
         Phone = "789-555-0189",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 202,
         Title = null,
         FirstName = "A.",
         MiddleName = "Francesca",
         LastName = "Leonetti",
         CompanyName = "Two-Seater Bikes",
         EmailAddress = "a0adventure-works.com",
         Phone = "645-555-0193",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 203,
         Title = "Ms.",
         FirstName = "Jean",
         MiddleName = null,
         LastName = "Jordan",
         CompanyName = "Separate Parts Corporation",
         EmailAddress = "jean3adventure-works.com",
         Phone = "207-555-0129",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 204,
         Title = "Mr.",
         FirstName = "Ido",
         MiddleName = null,
         LastName = "Ben-Sachar",
         CompanyName = "Traction Tire Company",
         EmailAddress = "ido0adventure-works.com",
         Phone = "973-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 205,
         Title = "Mr.",
         FirstName = "Frank",
         MiddleName = null,
         LastName = "Mart¡nez",
         CompanyName = "Rally Master Company Inc",
         EmailAddress = "frank5adventure-works.com",
         Phone = "171-555-0147",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 208,
         Title = "Mr.",
         FirstName = "Steve",
         MiddleName = null,
         LastName = "Masters",
         CompanyName = "Professional Cyclists",
         EmailAddress = "steve2adventure-works.com",
         Phone = "154-555-0115",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 209,
         Title = "Mr.",
         FirstName = "Robert",
         MiddleName = "E.",
         LastName = "Jones",
         CompanyName = "Purple Bicycle Company",
         EmailAddress = "robert6adventure-works.com",
         Phone = "595-555-0131",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 210,
         Title = "Mr.",
         FirstName = "Josh",
         MiddleName = null,
         LastName = "Barnhill",
         CompanyName = "Gasless Cycle Shop",
         EmailAddress = "josh0adventure-works.com",
         Phone = "584-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 214,
         Title = "Ms.",
         FirstName = "Jennifer",
         MiddleName = "J.",
         LastName = "Maxham",
         CompanyName = "Exclusive Bicycle Mart",
         EmailAddress = "jennifer1adventure-works.com",
         Phone = "1 (11) 500 555-0175",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 217,
         Title = "Mr.",
         FirstName = "Chris",
         MiddleName = null,
         LastName = "Maxwell",
         CompanyName = "City Manufacturing",
         EmailAddress = "chris6adventure-works.com",
         Phone = "642-555-0187",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 218,
         Title = "Mr.",
         FirstName = "David",
         MiddleName = null,
         LastName = "Johnson",
         CompanyName = "Sure & Reliable Sporting Goods",
         EmailAddress = "david18adventure-works.com",
         Phone = "476-555-0139",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 219,
         Title = "Mr.",
         FirstName = "Brian",
         MiddleName = null,
         LastName = "Johnson",
         CompanyName = "Extras Sporting Goods",
         EmailAddress = "brian6adventure-works.com",
         Phone = "320-555-0134",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 220,
         Title = "Mr.",
         FirstName = "Robert",
         MiddleName = null,
         LastName = "Brown",
         CompanyName = "Best o' Bikes",
         EmailAddress = "robert5adventure-works.com",
         Phone = "575-555-0189",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 221,
         Title = "Ms.",
         FirstName = "Sandra",
         MiddleName = "B.",
         LastName = "Maynard",
         CompanyName = "Bike Dealers Association",
         EmailAddress = "sandra4adventure-works.com",
         Phone = "993-555-0179",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 222,
         Title = "Mr.",
         FirstName = "Barry",
         MiddleName = null,
         LastName = "Johnson",
         CompanyName = "Sample Bike Store",
         EmailAddress = "barry1adventure-works.com",
         Phone = "858-555-0140",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 223,
         Title = "Ms.",
         FirstName = "Joyce",
         MiddleName = null,
         LastName = "Jarvis",
         CompanyName = "Paints and Solvents Company",
         EmailAddress = "joyce0adventure-works.com",
         Phone = "458-555-0179",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 226,
         Title = "Ms.",
         FirstName = "Vance",
         MiddleName = "P.",
         LastName = "Johns",
         CompanyName = "Leisure Activities",
         EmailAddress = "vance0adventure-works.com",
         Phone = "103-555-0151",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 227,
         Title = "Ms.",
         FirstName = "Robin",
         MiddleName = "M.",
         LastName = "McGuigan",
         CompanyName = "Health Spa, Limited",
         EmailAddress = "robin0adventure-works.com",
         Phone = "431-555-0153",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 228,
         Title = "Ms.",
         FirstName = "Danielle",
         MiddleName = "B.",
         LastName = "Johnson",
         CompanyName = "Home Town Bike Store",
         EmailAddress = "danielle1adventure-works.com",
         Phone = "356-555-0190",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 232,
         Title = "Mr.",
         FirstName = "David",
         MiddleName = null,
         LastName = "Jaffe",
         CompanyName = "Exceptional Cycle Services",
         EmailAddress = "david17adventure-works.com",
         Phone = "1 (11) 500 555-0140",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 235,
         Title = "Ms.",
         FirstName = "Mary",
         MiddleName = null,
         LastName = "Alexander",
         CompanyName = "Certified Bicycle Supply",
         EmailAddress = "mary7adventure-works.com",
         Phone = "344-555-0133",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 236,
         Title = "Ms.",
         FirstName = "Lola",
         MiddleName = "M.",
         LastName = "McCarthy",
         CompanyName = "Closeout Boutique",
         EmailAddress = "lola0adventure-works.com",
         Phone = "173-555-0151",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 237,
         Title = "Ms.",
         FirstName = "Mary",
         MiddleName = "K.",
         LastName = "Browning",
         CompanyName = "Client Discount Store",
         EmailAddress = "mary5adventure-works.com",
         Phone = "658-555-0146",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 238,
         Title = "Ms.",
         FirstName = "Jodan",
         MiddleName = "M.",
         LastName = "Jacobson",
         CompanyName = "A Great Bicycle Company",
         EmailAddress = "jodan0adventure-works.com",
         Phone = "652-555-0189",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 239,
         Title = "Ms.",
         FirstName = "Jane",
         MiddleName = "A.",
         LastName = "McCarty",
         CompanyName = "Bicycle Merchandise Warehouse",
         EmailAddress = "jane3adventure-works.com",
         Phone = "529-555-0195",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 240,
         Title = "Mr.",
         FirstName = "Jessie",
         MiddleName = "E.",
         LastName = "Valerio",
         CompanyName = "Wire Baskets and Parts",
         EmailAddress = "jessie0adventure-works.com",
         Phone = "103-555-0179",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 241,
         Title = "Mr.",
         FirstName = "Eric",
         MiddleName = "A.",
         LastName = "Jacobsen",
         CompanyName = "Vale Riding Supplies",
         EmailAddress = "eric5adventure-works.com",
         Phone = "703-555-0120",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 244,
         Title = "Mr.",
         FirstName = "Bronson",
         MiddleName = "R.",
         LastName = "Jacobs",
         CompanyName = "Retail Discount Store",
         EmailAddress = "bronson0adventure-works.com",
         Phone = "697-555-0131",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 245,
         Title = "Mr.",
         FirstName = "James",
         MiddleName = "L.",
         LastName = "McCoy",
         CompanyName = "Leather Seat Factory",
         EmailAddress = "james12adventure-works.com",
         Phone = "191-555-0151",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 246,
         Title = "Ms.",
         FirstName = "Esther",
         MiddleName = "K.",
         LastName = "Valle",
         CompanyName = "Large Bike Shop",
         EmailAddress = "esther0adventure-works.com",
         Phone = "481-555-0131",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 250,
         Title = "Ms.",
         FirstName = "Denean",
         MiddleName = "J.",
         LastName = "Ison",
         CompanyName = "Express Bike Services",
         EmailAddress = "denean0adventure-works.com",
         Phone = "1 (11) 500 555-0127",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 253,
         Title = "Mr.",
         FirstName = "Erik",
         MiddleName = null,
         LastName = "Ismert",
         CompanyName = "Roving Sports",
         EmailAddress = "erik0adventure-works.com",
         Phone = "116-555-0163",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 254,
         Title = "Mr.",
         FirstName = "Robert",
         MiddleName = "M.",
         LastName = "Bernacchi",
         CompanyName = "Safe Cycles Shop",
         EmailAddress = "robert4adventure-works.com",
         Phone = "449-555-0176",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 255,
         Title = "Mr.",
         FirstName = "Sunil",
         MiddleName = null,
         LastName = "Uppal",
         CompanyName = "Swift Cycles",
         EmailAddress = "sunil0adventure-works.com",
         Phone = "184-555-0187",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 256,
         Title = "Mr.",
         FirstName = "Richard",
         MiddleName = "L.",
         LastName = "Irwin",
         CompanyName = "Rental Bikes",
         EmailAddress = "richard4adventure-works.com",
         Phone = "367-555-0124",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 257,
         Title = "Mr.",
         FirstName = "Matthias",
         MiddleName = null,
         LastName = "Berndt",
         CompanyName = "Number 1 Supply",
         EmailAddress = "matthias1adventure-works.com",
         Phone = "384-555-0169",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 258,
         Title = "Mr.",
         FirstName = "Sairaj",
         MiddleName = null,
         LastName = "Uddin",
         CompanyName = "Quantity Discounts",
         EmailAddress = "sairaj1adventure-works.com",
         Phone = "767-555-0193",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 259,
         Title = "Mr.",
         FirstName = "Lucio",
         MiddleName = null,
         LastName = "Iallo",
         CompanyName = "Highway Bike Shop",
         EmailAddress = "lucio0adventure-works.com",
         Phone = "199-555-0135",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 262,
         Title = "Ms.",
         FirstName = "Beth",
         MiddleName = null,
         LastName = "Inghram",
         CompanyName = "General Industries",
         EmailAddress = "beth0adventure-works.com",
         Phone = "718-555-0152",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 263,
         Title = "Mr.",
         FirstName = "Timothy",
         MiddleName = "B.",
         LastName = "Burnett",
         CompanyName = "Farthest Bike Store",
         EmailAddress = "timothy0adventure-works.com",
         Phone = "251-555-0172",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 264,
         Title = "Ms.",
         FirstName = "Phyllis",
         MiddleName = "B.",
         LastName = "Tuffield",
         CompanyName = "Fasteners & Bolts Outlet",
         EmailAddress = "phyllis3adventure-works.com",
         Phone = "277-555-0182",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 268,
         Title = "Mr.",
         FirstName = "Richard",
         MiddleName = "A.",
         LastName = "Byham",
         CompanyName = "Channel Outlet",
         EmailAddress = "richard2adventure-works.com",
         Phone = "1 (11) 500 555-0138",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 271,
         Title = "Mr.",
         FirstName = "Jared",
         MiddleName = "L.",
         LastName = "Bustamante",
         CompanyName = "Alternative Vehicles",
         EmailAddress = "jared0adventure-works.com",
         Phone = "164-555-0147",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 272,
         Title = "Mr.",
         FirstName = "Henry",
         MiddleName = "L.",
         LastName = "Campen",
         CompanyName = "Metro Cycle Shop",
         EmailAddress = "henry0adventure-works.com",
         Phone = "635-555-0126",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 273,
         Title = "Ms.",
         FirstName = "Christie",
         MiddleName = "J.",
         LastName = "Trujillo",
         CompanyName = "A Typical Bike Shop",
         EmailAddress = "christie0adventure-works.com",
         Phone = "686-555-0180",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 274,
         Title = "Ms.",
         FirstName = "Janet",
         MiddleName = "J.",
         LastName = "Gilliat",
         CompanyName = "Active Systems",
         EmailAddress = "janet2adventure-works.com",
         Phone = "521-555-0183",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 275,
         Title = "Mr.",
         FirstName = "Chris",
         MiddleName = null,
         LastName = "Cannon",
         CompanyName = "Outdoor Sporting Goods",
         EmailAddress = "chris5adventure-works.com",
         Phone = "118-555-0131",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 276,
         Title = "Mr.",
         FirstName = "Michael John",
         MiddleName = "R.",
         LastName = "Troyer",
         CompanyName = "Thrifty Parts and Sales",
         EmailAddress = "michaeljohn0adventure-works.com",
         Phone = "308-555-0175",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 277,
         Title = "Mr.",
         FirstName = "Guy",
         MiddleName = null,
         LastName = "Gilbert",
         CompanyName = "The Bicycle Accessories Company",
         EmailAddress = "guy0adventure-works.com",
         Phone = "583-555-0198",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 280,
         Title = "Mr.",
         FirstName = "Frances",
         MiddleName = "J.",
         LastName = "Giglio",
         CompanyName = "Standard Bikes",
         EmailAddress = "frances1adventure-works.com",
         Phone = "692-555-0136",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 281,
         Title = "Ms.",
         FirstName = "Suzana De Abreu",
         MiddleName = "A.",
         LastName = "Canuto",
         CompanyName = "Petroleum Products Distributors",
         EmailAddress = "suzanadeabreu0adventure-works.com",
         Phone = "990-555-0141",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 282,
         Title = "Mr.",
         FirstName = "Billy",
         MiddleName = "J.",
         LastName = "Trent",
         CompanyName = "Quick Parts and Service",
         EmailAddress = "billy0adventure-works.com",
         Phone = "882-555-0115",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 286,
         Title = "Mr.",
         FirstName = "Leo",
         MiddleName = null,
         LastName = "Giakoumakis",
         CompanyName = "Number One Bike Co.",
         EmailAddress = "leo0adventure-works.com",
         Phone = "1 (11) 500 555-0169",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 287,
         Title = "Mr.",
         FirstName = "Grant",
         MiddleName = null,
         LastName = "Culbertson",
         CompanyName = "Handy Bike Services",
         EmailAddress = "grant1adventure-works.com",
         Phone = "859-555-0173",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 288,
         Title = "Mr.",
         FirstName = "Robert",
         MiddleName = "L.",
         LastName = "Barker",
         CompanyName = "Kickstand Sellers",
         EmailAddress = "robert3adventure-works.com",
         Phone = "241-555-0112",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 289,
         Title = "Ms.",
         FirstName = "Gabriel",
         MiddleName = "L.",
         LastName = "Bockenkamp",
         CompanyName = "Moderately-Priced Bikes Store",
         EmailAddress = "gabriel0adventure-works.com",
         Phone = "763-555-0145",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 290,
         Title = "Mr.",
         FirstName = "Scott",
         MiddleName = null,
         LastName = "Culp",
         CompanyName = "Friendly Bike Shop",
         EmailAddress = "scott3adventure-works.com",
         Phone = "119-555-0167",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 291,
         Title = "Mr.",
         FirstName = "Wayne",
         MiddleName = "N.",
         LastName = "Banack",
         CompanyName = "Grand Bicycle Stores",
         EmailAddress = "wayne0adventure-works.com",
         Phone = "640-555-0189",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 292,
         Title = "Mr.",
         FirstName = "Michael",
         MiddleName = "Greg",
         LastName = "Blythe",
         CompanyName = "Grease and Oil Products Company",
         EmailAddress = "michael11adventure-works.com",
         Phone = "126-555-0172",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 293,
         Title = "Mr.",
         FirstName = "Conor",
         MiddleName = null,
         LastName = "Cunningham",
         CompanyName = "Fashionable Bikes and Accessories",
         EmailAddress = "conor0adventure-works.com",
         Phone = "115-555-0113",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 294,
         Title = "Mr.",
         FirstName = "Alberto",
         MiddleName = "F.",
         LastName = "Baltazar",
         CompanyName = "Flawless Bike Shop",
         EmailAddress = "alberto0adventure-works.com",
         Phone = "780-555-0114",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 295,
         Title = "Mr.",
         FirstName = "Joseph",
         MiddleName = "P.",
         LastName = "Mitzner",
         CompanyName = "Engineered Bike Systems",
         EmailAddress = "joseph4adventure-works.com",
         Phone = "129-555-0164",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 298,
         Title = "Mr.",
         FirstName = "Robert",
         MiddleName = null,
         LastName = "Mitosinka",
         CompanyName = "City Cycling",
         EmailAddress = "robert10adventure-works.com",
         Phone = "239-555-0198",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 299,
         Title = "Mr.",
         FirstName = "Thierry",
         MiddleName = null,
         LastName = "D'Hers",
         CompanyName = "Citywide Service and Repair",
         EmailAddress = "thierry1adventure-works.com",
         Phone = "680-555-0192",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 300,
         Title = "Mr.",
         FirstName = "Daniel",
         MiddleName = null,
         LastName = "Blanco",
         CompanyName = "Nice Bikes",
         EmailAddress = "daniel0adventure-works.com",
         Phone = "221-555-0167",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 304,
         Title = "Ms.",
         FirstName = "Linda",
         MiddleName = null,
         LastName = "Mitchell",
         CompanyName = "Essential Bike Works",
         EmailAddress = "linda9adventure-works.com",
         Phone = "1 (11) 500 555-0182",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 306,
         Title = "Mr.",
         FirstName = "Stephen",
         MiddleName = "M.",
         LastName = "Ayers",
         CompanyName = "Work and Play Association",
         EmailAddress = "stephen1adventure-works.com",
         Phone = "818-555-0171",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 307,
         Title = "Ms.",
         FirstName = "Neva",
         MiddleName = "M.",
         LastName = "Mitchell",
         CompanyName = "Riding Associates",
         EmailAddress = "neva0adventure-works.com",
         Phone = "992-555-0134",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 308,
         Title = "Ms.",
         FirstName = "Megan",
         MiddleName = "N.",
         LastName = "Davis",
         CompanyName = "Rugged Bikes",
         EmailAddress = "megan1adventure-works.com",
         Phone = "839-555-0198",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 309,
         Title = "Mr.",
         FirstName = "John",
         MiddleName = null,
         LastName = "Arthur",
         CompanyName = "The Gear Store",
         EmailAddress = "john6adventure-works.com",
         Phone = "149-555-0113",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 310,
         Title = "Mr.",
         FirstName = "Frank",
         MiddleName = null,
         LastName = "Miller",
         CompanyName = "Orange Bicycle Company",
         EmailAddress = "frank6adventure-works.com",
         Phone = "118-555-0184",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 311,
         Title = "Sr.",
         FirstName = "Alvaro",
         MiddleName = null,
         LastName = "De Matos Miranda Filho",
         CompanyName = "Principal Bike Company",
         EmailAddress = "alvaro0adventure-works.com",
         Phone = "551-555-0155",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      },
      new Customer {
         CustomerID = 312,
         Title = "Mr.",
         FirstName = "Thomas",
         MiddleName = "B.",
         LastName = "Armstrong",
         CompanyName = "Resale Services",
         EmailAddress = "thomas1adventure-works.com",
         Phone = "226-555-0146",
         ModifiedDate = Convert.ToDateTime("10/13/2004 11:15:07 AM"),
      }
    };
  }
  #endregion

  #region Get Method
  /// <summary>
  /// Get a single Customer object
  /// </summary>
  /// <param name="id">The value to locate</param>
  /// <returns>A valid Customer object object, or null if not found</returns>
  public Customer? Get(int id) {
    return Get().Where(row => row.CustomerID == id).FirstOrDefault();
  }
  #endregion
}