using AdventureWorks.EntityLayer;
using Common.Library;
using System.Collections.ObjectModel;
using System.Data;

namespace AdventureWorks.DataLayer;

/// <summary>
/// This class creates some fake data for the Users.
/// </summary>
public partial class UserRepository : IRepository<User>
{
  #region GetAsync Method
  /// <summary>
  /// Get all User objects
  /// </summary>
  /// <returns>A list of User objects</returns>
  public async Task<ObservableCollection<User>> GetAsync()
  {
    return await Task.FromResult(new ObservableCollection<User>()
    {
            new User {
           UserId = 1,
           LoginId = @"MichaelThomason",
           FirstName = @"Michael",
           LastName = @"Thomason",
           Email = @"MichaelThomason@advworks.com",
           Phone = @"615.555.3333",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1985, 3, 15),
           StartTime = null,
        },
        new User {
           UserId = 2,
           LoginId = @"SheilaCleverly",
           FirstName = @"Sheila",
           LastName = @"Cleverly",
           Email = @"SheilaCleverly@advworks.com",
           Phone = @"615.123.3456",
           PhoneType = @"Other",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1981, 6, 9),
           StartTime = null,
        },
        new User {
           UserId = 3,
           LoginId = @"CatherineAbel",
           FirstName = @"Catherine",
           LastName = @"Abel",
           Email = @"CatherineAbel@advworks.com",
           Phone = @"615.998.3332",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1979, 4, 5),
           StartTime = null,
        },
        new User {
           UserId = 4,
           LoginId = @"KimAbercrombie",
           FirstName = @"Kim",
           LastName = @"Abercrombie",
           Email = @"KimAbercrombie@advworks.com",
           Phone = @"615.555.3333",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1995, 3, 8),
           StartTime = null,
        },
        new User {
           UserId = 7,
           LoginId = @"JimWalker",
           FirstName = @"Jim",
           LastName = @"Walker",
           Email = @"JimWalker@advworks.com",
           Phone = @"615.369.9372",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1999, 7, 29),
           StartTime = null,
        },
        new User {
           UserId = 8,
           LoginId = @"SamAbolrous",
           FirstName = @"Sam",
           LastName = @"Abolrous",
           Email = @"SamAbolrous@advworks.com",
           Phone = @"615.555.3333",
           PhoneType = @"Work",
           IsFullTime = false,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(2000, 12, 3),
           StartTime = TimeSpan.Parse("07:00:00"),
        },
        new User {
           UserId = 9,
           LoginId = @"RichardDudely",
           FirstName = @"Richard",
           LastName = @"Dudely",
           Email = @"RichardDudely@advworks.com",
           Phone = @"615.987.3782",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1997, 8, 23),
           StartTime = null,
        },
        new User {
           UserId = 10,
           LoginId = @"ScottBerton",
           FirstName = @"Scott",
           LastName = @"Berton",
           Email = @"ScottBerton@advworks.com",
           Phone = @"615.555.3333",
           PhoneType = @"Work",
           IsFullTime = false,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(2001, 2, 12),
           StartTime = TimeSpan.Parse("08:00:00"),
        },
        new User {
           UserId = 11,
           LoginId = @"PaulShaefer",
           FirstName = @"Paul",
           LastName = @"Shaefer",
           Email = @"Pauls@netinc.com",
           Phone = @"(714) 399-9212",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1963, 2, 5),
           StartTime = null,
        },
        new User {
           UserId = 12,
           LoginId = @"MichaelKawoski",
           FirstName = @"Michael",
           LastName = @"Kawoski",
           Email = @"Michaelk@netinc.com",
           Phone = @"(714) 939-0002",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1953, 7, 5),
           StartTime = null,
        },
        new User {
           UserId = 13,
           LoginId = @"SaraWinchell",
           FirstName = @"Sara",
           LastName = @"Winchell",
           Email = @"Saraw@netinc.com",
           Phone = @"(714) 738-9382",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = false,
           BirthDate = new DateTime(1978, 8, 2),
           StartTime = null,
        },
        new User {
           UserId = 14,
           LoginId = @"JohnKroon",
           FirstName = @"John",
           LastName = @"Kroon",
           Email = @"Johnk@netinc.com",
           Phone = @"(949) 667-7347",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1970, 3, 23),
           StartTime = null,
        },
        new User {
           UserId = 15,
           LoginId = @"TimNicker",
           FirstName = @"Tim",
           LastName = @"Nicker",
           Email = @"Timn@netinc.com",
           Phone = @"(714) 767-3747",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1975, 4, 5),
           StartTime = null,
        },
        new User {
           UserId = 16,
           LoginId = @"RussMartlog",
           FirstName = @"Russ",
           LastName = @"Martlog",
           Email = @"Russm@netinc.com",
           Phone = @"(714) 334-5643",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1969, 5, 5),
           StartTime = null,
        },
        new User {
           UserId = 17,
           LoginId = @"JohnBoron",
           FirstName = @"John",
           LastName = @"Boron",
           Email = @"Johnb@netinc.com",
           Phone = @"(714) 939-9993",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = false,
           BirthDate = new DateTime(1965, 3, 2),
           StartTime = null,
        },
        new User {
           UserId = 18,
           LoginId = @"JamesBirdy",
           FirstName = @"James",
           LastName = @"Birdy",
           Email = @"Jamesb@netinc.com",
           Phone = @"(310) 939-9932",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1966, 6, 23),
           StartTime = null,
        },
        new User {
           UserId = 19,
           LoginId = @"TreyChen",
           FirstName = @"Trey",
           LastName = @"Chen",
           Email = @"Treyc@netinc.com",
           Phone = @"(562) 991-0009",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1961, 7, 11),
           StartTime = null,
        },
        new User {
           UserId = 20,
           LoginId = @"JimJones",
           FirstName = @"Jim",
           LastName = @"Jones",
           Email = @"Jimj@netinc.com",
           Phone = @"(714) 223-0029",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1970, 1, 20),
           StartTime = null,
        },
        new User {
           UserId = 21,
           LoginId = @"JohnPittsburgh",
           FirstName = @"John",
           LastName = @"Pittsburgh",
           Email = @"Johnp@netinc.com",
           Phone = @"(714) 554-0493",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1978, 8, 6),
           StartTime = null,
        },
        new User {
           UserId = 22,
           LoginId = @"JeanneRussell",
           FirstName = @"Jeanne",
           LastName = @"Russell",
           Email = @"Jeanner@netinc.com",
           Phone = @"(949) 339-0000",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1966, 8, 15),
           StartTime = null,
        },
        new User {
           UserId = 23,
           LoginId = @"DavidLafeet",
           FirstName = @"David",
           LastName = @"Lafeet",
           Email = @"Davidl@netinc.com",
           Phone = @"(949) 399-9232",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1973, 10, 14),
           StartTime = null,
        },
        new User {
           UserId = 24,
           LoginId = @"KhanhVoon",
           FirstName = @"Khanh",
           LastName = @"Voon",
           Email = @"Khanhv@netinc.com",
           Phone = @"(714) 342-3232",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1962, 11, 20),
           StartTime = null,
        },
        new User {
           UserId = 25,
           LoginId = @"JimRussell",
           FirstName = @"Jim",
           LastName = @"Russell",
           Email = @"Jimr@netinc.com",
           Phone = @"(714) 123-2343",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1960, 12, 10),
           StartTime = null,
        },
        new User {
           UserId = 26,
           LoginId = @"DavidTarkas",
           FirstName = @"David",
           LastName = @"Tarkas",
           Email = @"Davidt@netinc.com",
           Phone = @"(714) 893-7361",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1967, 3, 15),
           StartTime = null,
        },
        new User {
           UserId = 27,
           LoginId = @"CraigShowman",
           FirstName = @"Craig",
           LastName = @"Showman",
           Email = @"Craigs@netinc.com",
           Phone = @"(949) 938-1234",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1974, 4, 6),
           StartTime = null,
        },
        new User {
           UserId = 28,
           LoginId = @"BrooksAnderson",
           FirstName = @"Brooks",
           LastName = @"Anderson",
           Email = @"Brooksa@netinc.com",
           Phone = @"(949) 777-3929",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1959, 8, 30),
           StartTime = null,
        },
        new User {
           UserId = 29,
           LoginId = @"MarkParks",
           FirstName = @"Mark",
           LastName = @"Parks",
           Email = @"Markp@netinc.com",
           Phone = @"(425) 377-7333",
           PhoneType = @"Mobile",
           IsFullTime = false,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1968, 10, 19),
           StartTime = TimeSpan.Parse("06:00:00"),
        },
        new User {
           UserId = 30,
           LoginId = @"KeithNashville",
           FirstName = @"Keith",
           LastName = @"Nashville",
           Email = @"Keithn@netinc.com",
           Phone = @"(702) 773-0093",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = true,
           IsActive = false,
           BirthDate = new DateTime(1972, 1, 31),
           StartTime = null,
        },
        new User {
           UserId = 31,
           LoginId = @"JaneJoan",
           FirstName = @"Jane",
           LastName = @"Joan",
           Email = @"Janej@netinc.com",
           Phone = @"(408) 939-9993",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = false,
           IsEnrolledInHSA = false,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1962, 12, 7),
           StartTime = null,
        },
        new User {
           UserId = 33,
           LoginId = @"BrianGossling",
           FirstName = @"Brian",
           LastName = @"Gossling",
           Email = @"BrianGossling@advworks.com",
           Phone = @"916.234.8372",
           PhoneType = @"Work",
           IsFullTime = true,
           IsEnrolledIn401k = false,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = false,
           IsActive = true,
           BirthDate = new DateTime(1993, 5, 16),
           StartTime = null,
        },
        new User {
           UserId = 34,
           LoginId = @"BenQueen",
           FirstName = @"Ben",
           LastName = @"Queen",
           Email = @"BenQueen@advworks.com",
           Phone = @"615.339.9032",
           PhoneType = @"Mobile",
           IsFullTime = true,
           IsEnrolledIn401k = true,
           IsEnrolledInHealthCare = true,
           IsEnrolledInHSA = true,
           IsEnrolledInFlexTime = true,
           IsActive = true,
           BirthDate = new DateTime(1996, 11, 1),
           StartTime = null,
        }
    });
  }
  #endregion

  #region GetAsync(id) Method
  /// <summary>
  /// Get a single User object
  /// </summary>
  /// <param name="id">The value to locate</param>
  /// <returns>A valid User object object, or null if not found</returns>
  public async Task<User?> GetAsync(int id)
  {
    ObservableCollection<User> list = await GetAsync();
    User? entity = list.Where(row => row.UserId == id).FirstOrDefault();

    return await Task.FromResult(entity);
  }
  #endregion
}