let rvs = [
  {
    "rvid": 1,
    "year": 2025,
    "make": "Newmar",
    "model": "Bay Star",
    "minLength": 30,
    "maxLength": 38,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 247100
  },
  {
    "rvid": 2,
    "year": 2025,
    "make": "Newmar",
    "model": "Dutch Star",
    "minLength": 38,
    "maxLength": 43,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 593775
  },
  {
    "rvid": 3,
    "year": 2025,
    "make": "Newmar",
    "model": "New Aire",
    "minLength": 35,
    "maxLength": 35,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 623935
  },
  {
    "rvid": 4,
    "year": 2025,
    "make": "Newmar",
    "model": "Ventana",
    "minLength": 35,
    "maxLength": 43,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 467625
  },
  {
    "rvid": 5,
    "year": 2025,
    "make": "Newmar",
    "model": "Super Star",
    "minLength": 37,
    "maxLength": 40,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 505326
  },
  {
    "rvid": 6,
    "year": 2025,
    "make": "Newmar",
    "model": "London Aire",
    "minLength": 45,
    "maxLength": 45,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 910940
  },
  {
    "rvid": 7,
    "year": 2025,
    "make": "Newmar",
    "model": "King Aire",
    "minLength": 45,
    "maxLength": 45,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 1637440
  },
  {
    "rvid": 8,
    "year": 2025,
    "make": "Newmar",
    "model": "Northern Star",
    "minLength": 34,
    "maxLength": 40,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 387234
  },
  {
    "rvid": 101,
    "year": 2025,
    "make": "Tiffin",
    "model": "Open Road Allegro",
    "minLength": 34,
    "maxLength": 38,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 288365
  },
  {
    "rvid": 102,
    "year": 2025,
    "make": "Tiffin",
    "model": "Allegro RED",
    "minLength": 35,
    "maxLength": 39,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 412544
  },
  {
    "rvid": 103,
    "year": 2025,
    "make": "Tiffin",
    "model": "Allegro Bus",
    "minLength": 37,
    "maxLength": 45,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 645933
  },
  {
    "rvid": 104,
    "year": 2025,
    "make": "Tiffin",
    "model": "Phaeton",
    "minLength": 37,
    "maxLength": 44,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 600149
  },
  {
    "rvid": 105,
    "year": 2025,
    "make": "Tiffin",
    "model": "Wayfarer",
    "minLength": 25,
    "maxLength": 25,
    "engineType": "Gas",
    "class": "C",
    "listPrice": 210216
  },
  {
    "rvid": 106,
    "year": 2025,
    "make": "Tiffin",
    "model": "Allegro Bay",
    "minLength": 38,
    "maxLength": 38,
    "engineType": "Diesel",
    "class": "C",
    "listPrice": 399717
  },
  {
    "rvid": 201,
    "year": 2025,
    "make": "Entegra",
    "model": "Anthem",
    "minLength": 37,
    "maxLength": 44,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 704850
  },
  {
    "rvid": 202,
    "year": 2025,
    "make": "Entegra",
    "model": "Vision XL",
    "minLength": 34,
    "maxLength": 38,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 204743
  },
  {
    "rvid": 203,
    "year": 2025,
    "make": "Entegra",
    "model": "Emblem",
    "minLength": 36,
    "maxLength": 38,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 240225
  },
  {
    "rvid": 204,
    "year": 2025,
    "make": "Entegra",
    "model": "Accolade",
    "minLength": 40,
    "maxLength": 40,
    "engineType": "Diesel",
    "class": "C",
    "listPrice": 355193
  },
  {
    "rvid": 205,
    "year": 2025,
    "make": "Entegra",
    "model": "Odyssey",
    "minLength": 24,
    "maxLength": 31,
    "engineType": "Gas",
    "class": "C",
    "listPrice": 159818
  },
  {
    "rvid": 301,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "Axis",
    "minLength": 24,
    "maxLength": 26,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 158340
  },
  {
    "rvid": 302,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "VeGas",
    "minLength": 24,
    "maxLength": 26,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 158340
  },
  {
    "rvid": 303,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "A.C.E.",
    "minLength": 30,
    "maxLength": 34,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 184660
  },
  {
    "rvid": 304,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "Luminate",
    "minLength": 31,
    "maxLength": 37,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 218260
  },
  {
    "rvid": 305,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "Indigo",
    "minLength": 31,
    "maxLength": 37,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 218260
  },
  {
    "rvid": 306,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "Outlaw Class A",
    "minLength": 38,
    "maxLength": 38,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 295350
  },
  {
    "rvid": 307,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "Palazzo GT",
    "minLength": 34,
    "maxLength": 39,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 298620
  },
  {
    "rvid": 308,
    "year": 2025,
    "make": "Thor Motor Coach",
    "model": "Aria",
    "minLength": 34,
    "maxLength": 42,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 394660
  },
  {
    "rvid": 401,
    "year": 2025,
    "make": "Winnebago",
    "model": "Adventurer",
    "minLength": 35,
    "maxLength": 37,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 252851
  },
  {
    "rvid": 402,
    "year": 2025,
    "make": "Winnebago",
    "model": "Vista",
    "minLength": 30,
    "maxLength": 35,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 208885
  },
  {
    "rvid": 403,
    "year": 2025,
    "make": "Winnebago",
    "model": "Sunstar",
    "minLength": 30,
    "maxLength": 35,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 208885
  },
  {
    "rvid": 404,
    "year": 2025,
    "make": "Winnebago",
    "model": "Forza",
    "minLength": 35,
    "maxLength": 40,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 361072
  },
  {
    "rvid": 405,
    "year": 2025,
    "make": "Winnebago",
    "model": "Journey",
    "minLength": 35,
    "maxLength": 35,
    "engineType": "Diesel",
    "class": "A",
    "listPrice": 480270
  },
  {
    "rvid": 406,
    "year": 2025,
    "make": "Winnebago",
    "model": "Minni Winnie",
    "minLength": 24,
    "maxLength": 32,
    "engineType": "Gas",
    "class": "A",
    "listPrice": 146248
  },
  {
    "rvid": 407,
    "year": 2025,
    "make": "Winnebago",
    "model": "Ekko",
    "minLength": 23,
    "maxLength": 23,
    "engineType": "Gas",
    "class": "C",
    "listPrice": 215551
  }
];