using System;
using System.Collections.Generic;
using System.Linq;
using AdventureWorks.EntityLayer;

namespace AdventureWorks.DataLayer;

/// <summary>
/// This class creates some fake data for the Users.
/// </summary>
public partial class UserRepository
{
  #region Get Method
  /// <summary>
  /// Get all User objects
  /// </summary>
  /// <returns>A list of User objects</returns>
  public List<User> Get()
  {
    return new List<User>
    {
      new User {
         UserId = 1,
         LoginId = @"PaulShaefer1",
         FirstName = @"Paul",
         LastName = @"Shaefer",
         Email = @"Pauls@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(615) 399-9212",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("2/5/1963 12:00:00 AM"),
      },
      new User {
         UserId = 2,
         LoginId = @"MichaelKawoski2",
         FirstName = @"Michael",
         LastName = @"Kawoski",
         Email = @"Michaelk@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"714.939.0002",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("7/5/1953 12:00:00 AM"),
      },
      new User {
         UserId = 3,
         LoginId = @"SaraWinchell3",
         FirstName = @"Sara",
         LastName = @"Winchell",
         Email = @"Saraw@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(714) 738-9382",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("8/2/1978 12:00:00 AM"),
      },
      new User {
         UserId = 4,
         LoginId = @"JohnKroon4",
         FirstName = @"John",
         LastName = @"Kroon",
         Email = @"Johnk@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"949.667.7347",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("3/23/1970 12:00:00 AM"),
      },
      new User {
         UserId = 5,
         LoginId = @"TimNicker5",
         FirstName = @"Tim",
         LastName = @"Nicker",
         Email = @"Timn@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(714) 767-3747",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("4/5/1975 12:00:00 AM"),
      },
      new User {
         UserId = 6,
         LoginId = @"RussMartlog6",
         FirstName = @"Russ",
         LastName = @"Martlog",
         Email = @"Russm@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"714-334-5643",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("5/5/1969 12:00:00 AM"),
      },
      new User {
         UserId = 7,
         LoginId = @"JohnBoron7",
         FirstName = @"John",
         LastName = @"Boron",
         Email = @"Johnb@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(714) 939-9993",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("3/2/1965 12:00:00 AM"),
      },
      new User {
         UserId = 8,
         LoginId = @"JamesBirdy8",
         FirstName = @"James",
         LastName = @"Birdy",
         Email = @"Jamesb@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"310-939-9932",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = false,
         IsActive = false,
         BirthDate = Convert.ToDateTime("6/23/1966 12:00:00 AM"),
      },
      new User {
         UserId = 9,
         LoginId = @"TreyChen9",
         FirstName = @"Trey",
         LastName = @"Chen",
         Email = @"Treyc@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(562) 991-0009",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = false,
         IsActive = true,
         BirthDate = Convert.ToDateTime("7/11/1961 12:00:00 AM"),
      },
      new User {
         UserId = 10,
         LoginId = @"JimJones10",
         FirstName = @"Jim",
         LastName = @"Jones",
         Email = @"Jimj@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(714) 223-0029",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("1/20/1970 12:00:00 AM"),
      },
      new User {
         UserId = 11,
         LoginId = @"JohnPittsburgh11",
         FirstName = @"John",
         LastName = @"Pittsburgh",
         Email = @"Johnp@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(714) 554-0493",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("8/6/1978 12:00:00 AM"),
      },
      new User {
         UserId = 12,
         LoginId = @"JeanneRussell12",
         FirstName = @"Jeanne",
         LastName = @"Russell",
         Email = @"Jeanner@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(949) 339-0000",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("8/15/1966 12:00:00 AM"),
      },
      new User {
         UserId = 13,
         LoginId = @"DavidLafeet13",
         FirstName = @"David",
         LastName = @"Lafeet",
         Email = @"Davidl@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(949) 399-9232",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = false,
         IsActive = true,
         BirthDate = Convert.ToDateTime("10/14/1973 12:00:00 AM"),
      },
      new User {
         UserId = 14,
         LoginId = @"KhanhVoon14",
         FirstName = @"Khanh",
         LastName = @"Voon",
         Email = @"Khanhv@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"714-342-3232",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = false,
         IsActive = false,
         BirthDate = Convert.ToDateTime("11/20/1962 12:00:00 AM"),
      },
      new User {
         UserId = 15,
         LoginId = @"JimRussell15",
         FirstName = @"Jim",
         LastName = @"Russell",
         Email = @"Jimr@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(615) 123-2343",
         PhoneType = @"Home",
         IsEnrolledIn401k = true,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("12/10/1960 12:00:00 AM"),
      },
      new User {
         UserId = 16,
         LoginId = @"DavidTarkas16",
         FirstName = @"David",
         LastName = @"Tarkas",
         Email = @"Davidt@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"7148937361",
         PhoneType = @"Home",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = true,
         IsEnrolledInHSA = true,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("3/15/1967 12:00:00 AM"),
      },
      new User {
         UserId = 17,
         LoginId = @"CraigShowman17",
         FirstName = @"Craig",
         LastName = @"Showman",
         Email = @"Craigs@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(949) 938-1234",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("4/6/1974 12:00:00 AM"),
      },
      new User {
         UserId = 18,
         LoginId = @"BrooksAnderson18",
         FirstName = @"Brooks",
         LastName = @"Anderson",
         Email = @"Brooksa@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(949) 777-3929",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = true,
         BirthDate = Convert.ToDateTime("8/30/1959 12:00:00 AM"),
      },
      new User {
         UserId = 19,
         LoginId = @"MarkParks19",
         FirstName = @"Mark",
         LastName = @"Parks",
         Email = @"Markp@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"4253777333",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = true,
         IsActive = false,
         BirthDate = Convert.ToDateTime("10/19/1968 12:00:00 AM"),
      },
      new User {
         UserId = 20,
         LoginId = @"KeithNashville20",
         FirstName = @"Keith",
         LastName = @"Nashville",
         Email = @"Keithn@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(702) 773-0093",
         PhoneType = @"Home",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = false,
         IsActive = false,
         BirthDate = Convert.ToDateTime("1/31/1972 12:00:00 AM"),
      },
      new User {
         UserId = 21,
         LoginId = @"JaneJoan21",
         FirstName = @"Jane",
         LastName = @"Joan",
         Email = @"Janej@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(408) 939-9993",
         PhoneType = @"Home",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = false,
         IsActive = true,
         BirthDate = Convert.ToDateTime("12/7/1962 12:00:00 AM"),
      },
      new User {
         UserId = 23,
         LoginId = @"SteveNylander23",
         FirstName = @"Steve",
         LastName = @"Nylander",
         Email = @"stevenylander@paulsautoparts.com",
         Password = @"P@ssw0rd",
         Phone = @"(615) 338-0012",
         PhoneType = @"Mobile",
         IsEnrolledIn401k = false,
         IsEnrolledInHealthCare = false,
         IsEnrolledInHSA = false,
         IsEnrolledInFlexTime = false,
         IsActive = false,
         BirthDate = Convert.ToDateTime("3/4/1973 12:00:00 AM"),
      }
    }.OrderBy(row => row.LastName).ToList();
  }
  #endregion

  #region Get Method
  /// <summary>
  /// Get a single User object
  /// </summary>
  /// <param name="id">The value to locate</param>
  /// <returns>A valid User object object, or null if not found</returns>
  public User? Get(int id)
  {
    return Get().Where(row => row.UserId == id).FirstOrDefault();
  }
  #endregion
}